name: Version Incrementor

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    uses: ActionsCI/reusable-workflows/.github/workflows/version-incrementor.yaml@a22e31046645c43f004550e02c8d5b553ab7cb51
    secrets: inherit
